// <auto-generated />
using System;
using Catalog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260225000001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Models.Collection", b =>
            {
                b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at").HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp with time zone");
                b.Property<string>("Description").HasColumnName("description").HasColumnType("text");
                b.Property<int>("DisplayOrder").HasColumnName("display_order").HasDefaultValue(0).HasColumnType("integer");
                b.Property<string>("Image").HasColumnName("image").HasColumnType("text");
                b.Property<bool>("IsActive").HasColumnName("is_active").HasColumnType("boolean");
                b.Property<string>("Name").IsRequired().HasColumnName("name").HasColumnType("text");
                b.Property<string>("ParentId").HasColumnName("parent_id").HasColumnType("text");
                b.Property<string>("Slug").IsRequired().HasColumnName("slug").HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("ParentId").HasDatabaseName("IX_collections_parent_id");
                b.HasIndex("Slug").IsUnique().HasDatabaseName("IX_collections_slug");
                b.ToTable("collections");
            });

            modelBuilder.Entity("Catalog.Models.Product", b =>
            {
                b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
                b.Property<string>("CollectionId").IsRequired().HasColumnName("collection_id").HasColumnType("text");
                b.Property<string>("CollectionSlug").IsRequired().HasColumnName("collection_slug").HasColumnType("text");
                b.Property<decimal?>("CompareAtPrice").HasPrecision(10, 2).HasColumnName("compare_at_price").HasColumnType("numeric(10,2)");
                b.Property<DateTime>("CreatedAt").HasColumnName("created_at").HasDefaultValueSql("CURRENT_TIMESTAMP").HasColumnType("timestamp with time zone");
                b.Property<string>("Description").HasColumnName("description").HasColumnType("text");
                b.Property<bool>("IsActive").HasColumnName("is_active").HasColumnType("boolean");
                b.Property<string>("Name").IsRequired().HasColumnName("name").HasColumnType("text");
                b.Property<decimal>("Price").HasPrecision(10, 2).HasColumnName("price").HasColumnType("numeric(10,2)");
                b.Property<string>("ThumbnailImage").IsRequired().HasColumnName("thumbnail_image").HasColumnType("text");
                b.Property<int>("TotalStock").HasColumnName("total_stock").HasDefaultValue(0).HasColumnType("integer");
                b.Property<string>("VariantImages").IsRequired().HasColumnName("variant_images").HasColumnType("text");
                b.Property<string>("VariantOptions").IsRequired().HasColumnName("variant_options").HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("CollectionId").HasDatabaseName("IX_products_collection_id");
                b.HasIndex("CollectionSlug").HasDatabaseName("IX_products_collection_slug");
                b.ToTable("products");
            });

            modelBuilder.Entity("Catalog.Models.ProductSku", b =>
            {
                b.Property<string>("Id").HasColumnName("id").HasColumnType("text");
                b.Property<bool>("IsActive").HasColumnName("is_active").HasColumnType("boolean");
                b.Property<decimal?>("PriceOverride").HasPrecision(10, 2).HasColumnName("price_override").HasColumnType("numeric(10,2)");
                b.Property<string>("ProductId").IsRequired().HasColumnName("product_id").HasColumnType("text");
                b.Property<string>("SkuCode").IsRequired().HasColumnName("sku_code").HasColumnType("text");
                b.Property<int>("Stock").HasColumnName("stock").HasDefaultValue(0).HasColumnType("integer");
                b.Property<string>("VariantValues").IsRequired().HasColumnName("variant_values").HasColumnType("text");
                b.HasKey("Id");
                b.HasIndex("ProductId").HasDatabaseName("IX_product_skus_product_id");
                b.HasIndex("ProductId", "SkuCode").IsUnique().HasDatabaseName("IX_product_skus_product_id_sku_code");
                b.ToTable("product_skus");
            });

            modelBuilder.Entity("Catalog.Models.Collection", b =>
            {
                b.HasOne("Catalog.Models.Collection", null)
                    .WithMany()
                    .HasForeignKey("ParentId")
                    .OnDelete(DeleteBehavior.SetNull);
            });

            modelBuilder.Entity("Catalog.Models.ProductSku", b =>
            {
                b.HasOne("Catalog.Models.Product", null)
                    .WithMany()
                    .HasForeignKey("ProductId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
#pragma warning restore 612, 618
        }
    }
}
